##### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for Arrays and Matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
import numpy as np

## create array (1D) using numpy

arr1 = np.array([1,2,3,4,5])
print(arr1)  # [1 2 3 4 5]
print(type(arr1))  # <class 'numpy.ndarray'> (Here ndarray means n-dimensional array)

## To see the shape of the array
print(arr1.shape)  # (5,) -> Here, single digit signifies a 1D Array

In [ ]:
## Let's reshape it to a 2D Array

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  # array([[1, 2, 3, 4, 5]]) -> A 2D array has 2 square brackets opening and 2 square brackets closing
# Here, (1,5) means 1 row and 5 cols

In [ ]:
## You can also create a 2D array directly

arr2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr2)

'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
'''

print(arr2.shape)  # (2, 6) -> 2 rows and 6 cols

In [ ]:
## Inbuilt Functions in numpy

np.arange(0,10,2)  # array([0, 2, 4, 6, 8]) -> (start, stop, step) This is a 1D Array

np.arange(0,10,2).reshape(5,1)  # We are reshaping this to 2D Array with 5 rows and 1 col

'''
array([[0],
       [2],
       [4],
       [6],
       [8]])
'''


In [ ]:
np.ones((3,4))  # This will initialize an array with all 1's having 3 rows and 4 cols.

'''
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
'''

In [ ]:
## Identity Matrix

np.eye(3)  ## All the diagonal elements will be 1, rest will be 0

'''
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
'''

In [ ]:
## Attributes of numpy array

arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Number of Dimensions:\n", arr.ndim)
print("Size (number of elements):\n", arr.size)
print("Data Type:\n", arr.dtype)
print("Item size in bytes:\n", arr.itemsize)

'''
Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of Dimensions:
 2
Size (number of elements):
 6
Data Type:
 int64
Item size in bytes:
 8
'''

In [ ]:
## Numpy Vectorized Operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise Addition

print("Addition:", arr1+arr2)

## Element wise Subtraction

print("Subtraction:", arr1-arr2)

## Element wise Multiplication

print("Multiplication:", arr1*arr2)

## Element wise Division

print("Division:", arr1/arr2)

'''
Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
'''

In [ ]:
## Universal Functions

arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine

print(np.sin(arr))

## Log

print(np.log(arr))

'''
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
'''

In [ ]:
## Array Slicing and Indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
'''

## To retrive the 1st element

print(arr[0][0])  # 1

## Suppose you want to retrive the elements : 7,8,11,12

## Focus on the row and column index

print(arr[1:])

'''
[[ 5  6  7  8]
 [ 9 10 11 12]] -> This (1:) will print everything after the 1st row
'''

print(arr[1:,2:])

'''
[[ 7  8]
 [11 12]] -> This (1:,2:) will print everything after 1st row but only the columns starting with index 2
'''

## Suppose now we want to retrieve the elements 3,4,7,8

print(arr[0:2, 2:])

'''
[[3 4]
 [7 8]] -> This [0:2] specifies iterate only on 0th and 1st rows and for the cols starting from the 2nd one
'''

## Retrieve 6,7,10,11

print(arr[1:, 1:3])

'''
[[ 6  7]
 [10 11]]
'''

In [ ]:
## Modify Array Elements

arr[0][0] = 100
print(arr)

'''
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
'''

arr[1:] = 100
print(arr)

'''
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
'''

In [ ]:
## Statistical Concept - Normalization

## To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation

mean = np.mean(arr)
std_dev = np.std(arr)

## Normalize the data

normalized_data = (data - mean) / std_dev
print("Normalize Data:", normalized_data)  

'''
Normalize Data: [-1.77958327 -1.75577613 -1.731969   -1.70816186 -1.68435473]
'''

In [ ]:
## Some more statistical concepts

data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
print("Mean:", np.mean(data))  # Mean: 5.5

## Median
print("Median:", np.median(data))  # Median: 5.5

# Standard Deviation
print("Standard Deviation:", np.std(data))  # Standard Deviation: 2.8722813232690143

# Variance
print("Variance:", np.var(data))  # Variance: 8.25

In [ ]:
## Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data > 5]  # array([ 6,  7,  8,  9, 10])

data[(data > 5) & (data < 8)]  # array([6, 7])